# Generated by Django 5.1.2 on 2024-10-18 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drive", "0002_alter_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="name",
        ),
    ]
