# Generated by Django 5.1.2 on 2024-11-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
